### ISSUE TITLE
Separate access and preservation storage

### ISSUE THREAD

**Issue by ahankinson** [OCFL/Use-Cases#1]
An institution decides that it will employ an institutional repository system that does not implement OCFL, but that it wishes to use OCFL for long-term preservation. They implement OCFL on their long-term nearline storage (e.g., Amazon Glacier) as well as the preferred layout for storing to tape. They may employ the Export-only access pattern to dump changes periodically to an OCFL storage system, and then implement a  server-agnostic OCFL client to upload and update digital objects on an S3 system.

**Comment by zimeon** [comment]
I think this use case is quite reasonable but essentially `out-of-scope` for OCFL: Since OCFL is a file layout specification, it supports use cases that rely on a well defined file layout separate from any server that may use the same file layout. Independent access to OCFL objects would benefit from notions of validity/completeness and perhaps from a locking mechanism to avoid race conditions on update.

**Comment by ahankinson** [comment]
F2F 2018.09.05: Decided out of scope. This is a useful background but has no bearing on the spec itself.
