### ISSUE TITLE
Purging/permanent deletion of individual files

### ISSUE THREAD

**Issue by tomwrobel** [OCFL/Use-Cases#17]
An institution accepts a dataset from a researcher containing a number of binary files. On subsequent review, one of these files contains personally identifiable medical information. The file needs to be removed permanently from the file system.

**Comment by ahankinson** [comment]
A note from our conversations at LDCX where this came up: 

Moab does not allow file deletion -- if you put a file in, your options are to create a new version that removes those files from view (but they still exist in the object) or delete the object entirely and start anew.

With entire-object deletion, however, it was noted that all history of the object would be lost as it might get a new identifier, and the version history would be wiped. This might not be desired, as valuable version information might get lost if the only option is the 'nuclear' option.

**Comment by ahankinson** [comment]
F2F 2018.09.05: In the spec in the section on removing files. 

There are two bits of language:
 - "Delete" -- remove in most recent version
 - "Purge" -- remove from all versions

Delete is supported as a fundamental action of OCFL clients. Purging behaviours are not specified as part of the spec, but recommendations are that OCFL Object versions SHOULD BE immutable (following digital preservation best practices), BUT clients MAY decide otherwise, as long as the end result is a valid OCFL Object

**Comment by awoods** [comment]
Supported since v0.1 (impl-notes)
