### ISSUE TITLE
Use OCFL as wrapper for different underlying digital objects

### ISSUE THREAD

**Issue by julianmorley** [OCFL/Use-Cases#20]
e.g. allow Bagit and Moab objects to co-exist in a repository with a single inventory/manifest without needing to migrate Bagit objects into Moab.

**Comment by rosy1280** [comment]
for clarification a Bag inside a Moab object is a Bag in Moab's data directory.  It sounds like what @julianmorley is asking is if we can contain other object models within OCFL...

I do think there is a different between a Bag (which can just be a method of transport) and Moab (which is a way of modeling preservation objects), or PCDM (which is a way of modeling objects).

In my mind I would need to figure out a way to convert a PCDM object into OCFL **_OR_** I would need to figure out a way to convert an OCFL object (assuming I store in OCFL) into a Moab if i were to transfer to someone that needed Moab.  A bag i would just store as a file most likely, but I could be convinced otherwise...

**Comment by ahankinson** [comment]
F2F 2018.09.08: OCFL is content-agnostic; you can use it to wrap any type of bitstream.
